{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "code-server.serviceAccountName" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.serviceAccount.role.name }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.serviceAccount.role.namespaced }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "code-server.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.serviceAccount.role.namespaced }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Values.serviceAccount.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "code-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.serviceAccount.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.serviceAccount.role.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ .Values.serviceAccount.role.name }}
rules:
  {{- toYaml .Values.serviceAccount.role.rules | nindent 2 }}
{{- end }}
{{- end }}
