apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.k3dPort }}
      targetPort: k3d
      protocol: TCP
      name: k3d
  selector:
    {{- include "code-server.selectorLabels" . | nindent 4 }}
