{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistentVolumeClaim }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- else if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .requestSize }}
  {{- end }}
{{- end }}
---
{{- if and .Values.dind.enabled .Values.dind.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  {{- with .Values.dind.persistentVolumeClaim }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- else if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .requestSize }}
  {{- end }}
{{- end }}