apiVersion: v2
name: cosmo-controller-manager
description: COSMO Controller Manager Helm chart for Kubernetes
type: application
version: 0.16.9
appVersion: v0.16.9
kubeVersion: ">= 1.19.0"
home: https://github.com/cosmo-workspace/cosmo
icon: https://raw.githubusercontent.com/cosmo-workspace/cosmo/main/logo/logo-square-small.png
sources:
  - https://github.com/cosmo-workspace/cosmo/charts
maintainers:
  - name: jlandowner
    url: https://github.com/jlandowner
    email: jlandowner8@gmail.com
keywords:
  - cosmo